自動拋錯以及結構調整
udea-io/sails-hook-req-validate pull request #5
Opened 2021-07-08 07:00 UTC by rsghost

2021-07-08 12:49 UTC, iamcxa commented on lib/index.js
> +    if (!_.isNull(error) && config.autoThrowError) {
https://lodash.com/docs/4.17.15#isNil

改用這個判斷

2021-07-08 12:49 UTC, iamcxa commented on lib/index.js
> +      result = _.isNull(error) ? data : false;
理論上 autoThrowError 且有 error 時應該不會進到這個判斷，這裡應該是多的？

2021-07-08 12:49 UTC, iamcxa commented on lib/index.js
> +      result = _isNull(error) ? {
改 _.isNil，判斷範圍比較廣

這個 `_isNull` 是正確的嗎？

2021-07-08 12:49 UTC, iamcxa commented on test/bdd/09.demo.test.js
> +      // custom2: 1, // val > 1
這個是故意註解的嗎？還是改完忘了改回來？因為剛好跟本來的相反

2021-07-09 06:51 UTC, rsghost commented on lib/index.js
> +    if (!_.isNull(error) && config.autoThrowError) {
已修正

2021-07-09 06:51 UTC, rsghost commented on lib/index.js
> +      result = _.isNull(error) ? data : false;
已修正

2021-07-09 06:51 UTC, rsghost commented on lib/index.js
> +      result = _isNull(error) ? {
已修正

2021-07-09 06:51 UTC, rsghost commented on test/bdd/09.demo.test.js
> +      // custom2: 1, // val > 1
原本的測試有誤沒有改回來, 在這邊作修正

2021-07-10 04:10 UTC, iamcxa requested changes

2021-07-10 04:10 UTC, iamcxa commented on lib/index.js
> +      result = _isNil(error) ? {
@rsghost 這裏應該是有錯？我找不到 _isNil 這個 function？

2021-07-12 06:20 UTC, rsghost commented on lib/index.js
> +      result = _isNil(error) ? {
已修正

2021-07-12 16:00 UTC, merged